### PR TITLE
Fix timesheet widget

### PR DESCRIPTION
**Pull request by ghost**
When the timesheet is saved, if the unit_amount is 0, then it must be unlinked.

### CODE REVIEW

**Comment by guewen** [comment]
code review :+1:

**Comment by ghost** [comment]
@max3903 Could you review this pull request please ?

**Comment by ghost** [comment]
@max3903 can we merge this ? Also, I think I should be maintainer of this repository.

**Comment by max3903** [comment]
@dufresnedavid Can you bump the version? Otherwise :+1: 

You need to join the PSC to maintain this repo. Email the contributors ML, I am sure existing PSC members will endorse your application.

ping @OCA/project-service-maintainers

**Pull request merged**
