### PR TITLE
Wip redmine connector 3 v10

### PR DESCRIPTION
**Pull request by yucer**
This is a new port attempt of the **connector_redmine** to *version 10.0*.

Now includes also a port for **redmine_import_time_entry**

### CODE REVIEW

**Comment by yucer** [comment]
The commit sequence was rewritten from a previous port attempt, in order to keep the history.

**Comment by yucer** [comment]
During the manual test I get this error when using the button "Import from Redmine" in the timesheets.

```
2017-04-04 14:32:19,375 540 ERROR demo odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/lib/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/lib/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/lib/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/lib/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/lib/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/lib/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/lib/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/lib/odoo/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/lib/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/lib/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/lib/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/lib/addons/oca-connector-redmine/redmine_import_time_entry/models/hr_timesheet_sheet.py", line 54, in import_timesheets_from_redmine
    backend, employee.user_id.login, self.date_from, self.date_to)
  File "/opt/odoo/lib/addons/oca-connector-redmine/redmine_import_time_entry/unit/import_synchronizer.py", line 131, in import_single_user_time_entries
    return importer.run_single_user(filters=filters)
  File "/opt/odoo/lib/addons/oca-connector-redmine/redmine_import_time_entry/unit/import_synchronizer.py", line 67, in run_single_user
    user_id = self.backend_adapter.search_user(login)
  File "/opt/odoo/lib/addons/oca-connector-redmine/connector_redmine/unit/backend_adapter.py", line 58, in search_user
    (user.id for user in users if user.login == login), False)
  File "/usr/local/lib/python2.7/dist-packages/redmine/resultsets.py", line 102, in __iter__
    self._evaluate()
  File "/usr/local/lib/python2.7/dist-packages/redmine/resultsets.py", line 81, in _evaluate
    offset=self.manager.params.get('offset', self.offset)
  File "/usr/local/lib/python2.7/dist-packages/redmine/managers.py", line 62, in retrieve
    response = self.redmine.request('get', self.url, params=dict(self.params, limit=limit, offset=offset))
  File "/usr/local/lib/python2.7/dist-packages/redmine/__init__.py", line 134, in request
    raise ForbiddenError
```

this code from previous versions:

```
  File "/opt/odoo/lib/addons/oca-connector-redmine/connector_redmine/unit/backend_adapter.py", line 58, in search_user
    (user.id for user in users if user.login == login), False)
```

...performs this _REST query_ to **redmine**:

`$ curl -v 'https://my.redmine.server/users.json' -H 'X-Redmine-API-Key: 073...989'`

but such a query to all users seems to be **forbidden** in _redmine_. I found no combination of roles or setting in **standard redmine** that allows that operation.

There is an [open issue](http://www.redmine.org/issues/7773) in redmine regarding that. It seems not to be solved yet, although a patch is **adviced** by the community. It states:

> only a user logged in as a Redmine administrator can get a list of user

But the **odoo addon** make the query using the **active odoo user**. It even [warns about that](https://github.com/OCA/connector-redmine/blob/8.0/connector_redmine/README.rst) as mandatory:

> Be aware that the user login must be the same in both systems.

Do the original *addon* from **OCA** need such a patch for the redmine server in order to work?

**Comment by ghost** [comment]
@yucer the module does not use the active user to log in to Redmine, it uses the admin user. In Redmine, for now, until a patch is released (no idea when this might happen), only the admin can fetch the list of users.

**Comment by yucer** [comment]
@dufresnedavid but the module says in the description:

> Be aware that the user login must be the same in both systems.

Does it means that only the **admin** user from odoo can use the feature ?

**Comment by ghost** [comment]
@yucer no, any user can use the feature. The admin user is used as proxy to query the entries from redmine. But any user can use the feature. The only restriction is that the connector's config must contain the redmine api key of the admin user.

**Comment by tafaRU** [comment]
@yucer, trying to install `connector_redmine` provided by this PR I faced https://github.com/OCA/connector-redmine/issues/16 Any hints?

**Comment by tafaRU** [comment]
@yucer, @dufresnedavid, do you plan to continue working on this?

**Comment by yucer** [comment]
@tafaRU I did try, but the port was not complete. Actually I was taking it as an exercise to keep in touch with the breaking changes in the connector architecture.

I have little time currently for improve it. I didn't receive to much feedback so I guess the same happen with the creators.

Any other contributor can revert my changes when needed.

**Comment by tafaRU** [comment]
@yucer, thank you for your answer.

> but the port was not complete

Would you kindly highlight me which parts still need to be completed?
Just to know in order to continue working on this.

Thank you in advance.

**Comment by eLBati** [comment]
I'm taking care of this porting at
https://github.com/eLBati/connector-redmine/tree/10.0-redmine-connector-lb

I am about to migrate the connector API part http://odoo-connector.com/guides/migration_guide.html#declaration-of-a-job

**Comment by eLBati** [comment]
Moving to https://github.com/OCA/connector-redmine/pull/19
I think this can be closed

**Comment by yucer** [comment]
@tafaRU Sorry for not responding before. But I got the idea that I did reply in a related thread.

I was just trying to get the modules loaded but, when using it, there was was some issue related to the credentials used and the latest **redmine**. 

I guess you can follow @eLBati contributions now.

**Pull request closed without merging**
