### PR TITLE
Wip redmine connector 2 v10

### PR DESCRIPTION
**Pull request by yucer**
Migration of v8 to v10.

Every adjust stays in a different commit with the explanation.

Now the module is able to load, and make a successful connect to redmine.

Unfortunately I have no used the v8 module before.

I need feedback to check if something is missing.

What should I do after the test connection succeed?

What should I do in the user interface to transfer the time sheets ?

(attempt #2. fixed pep8 and tests)

### CODE REVIEW

**Comment by ghost** [comment]
@yucer no raw copy please. Use git merge. Thanks

**Comment by yucer** [comment]
Actually I made a "manual merge"... because there was a base code there in v10.

But ok, I will try with merge at this first commit.

I am also checking the other errors from travis.

Thanks.

**Comment by ghost** [comment]
@yucer no manual merge as you call it. I want to keep the history of commits from the beggining.

**Comment by tafaRU** [comment]
Is superseded by https://github.com/OCA/connector-redmine/pull/15?
Can this be closed?

**Pull request closed without merging**
